services:
  - type: web
    name: mpower-app
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/test
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false